---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: amq-streams
  name: mllp2kafka-user
  namespace: VAR.NAMESPACE
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: All
        host: '*'
      - resource:
          type: group
          name: '*'
          patternType: literal
        operation: All
        host: '*'
      - resource:
          type: cluster
        operation: All
        host: '*'
      - resource:
          type: transactionalId
          name: '*'
          patternType: literal
        operation: All
        host: '*'
    type: simple
