---
apiVersion: broker.amq.io/v2alpha2
kind: ActiveMQArtemisAddress
metadata:
  name: amq-address-test1
  namespace: VAR.NAMESPACE
spec:
  addressName: test1
  queueName: test1
  routingType: anycast
  removeFromBrokerOnDelete: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camel-paho2kafka
    app.kubernetes.io/component: camel-paho2kafka
    app.kubernetes.io/instance: camel-paho2kafka
  name: camel-paho2kafka
  namespace: VAR.NAMESPACE
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: camel-paho2kafka
  template:
    metadata:
      labels:
        deployment: camel-paho2kafka
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: deployment
                operator: In
                values:
                - camel-paho2kafka
            topologyKey: kubernetes.io/hostname
      containers:
      - image: VAR.IMAGE.AMQBROKER.PAHO2KAFKA
        name: camel-paho2kafka
        ports:
        - containerPort: 8778
          protocol: TCP
          name: jolokia
        - containerPort: 9779
          protocol: TCP
          name: web
        env:
          - name: AB_JOLOKIA_AUTH_OPENSHIFT
            value: 'false'
          - name: AB_JOLOKIA_PASSWORD_RANDOM
            value: 'false'
          - name: AB_JOLOKIA_OPTS
            value: 'useSslClientAuthentication=false,protocol=https'
        resources: 
          limits:
            memory: VAR.PAHO2KAFKA.MEMORY
            cpu: VAR.PAHO2KAFKA.CPU
          requests:
            cpu: VAR.PAHO2KAFKA.CPU
            memory: VAR.PAHO2KAFKA.MEMORY
        volumeMounts:
        - mountPath: /deployments/config/application.properties
          name: camel-paho2kafka-config
          subPath: application.properties
      volumes:
      - configMap:
          defaultMode: 420
          name: camel-paho2kafka-config
        name: camel-paho2kafka-config
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: camel-paho2kafka-metrics
  namespace: VAR.NAMESPACE
  labels:
    team: fuse
spec:
  selector:
    matchLabels:
      deployment: camel-paho2kafka
  namespaceSelector:
    matchNames:
      - VAR.NAMESPACE
  podMetricsEndpoints:
  - path: /
    port: web
---
apiVersion: v1
data:
  application.properties: |
    # Keep Camel Route Alive
    camel.springboot.main-run-controller = true

    camel.component.paho.topic=test1
    camel.component.paho.serverURIs=tcp://amq-broker-hdls-svc:61616
    camel.component.paho.qos=2
    camel.component.paho.password=password
    camel.component.paho.userName=user1

    topics=paho2kafka-test1
    camel.component.kafka.configuration.brokers=amq-streams-kafka-bootstrap:9092
    camel.component.kafka.configuration.security-protocol=SASL_PLAINTEXT
    camel.component.kafka.configuration.sasl-mechanism=SCRAM-SHA-512
    camel.component.kafka.configuration.sasl-jaas-config=VAR.PAHO2KAFA_SASL_JAAS_CONFIG.VALUE
kind: ConfigMap
metadata:
  name: camel-paho2kafka-config
  namespace: VAR.NAMESPACE
